@Cart.Api_HostAddress = http://localhost:5233

GET {{Cart.Api_HostAddress}}/api/v1/cart/user-123
Accept: application/json

###

POST {{Cart.Api_HostAddress}}/api/v1/cart/user-123/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

###

PUT {{Cart.Api_HostAddress}}/api/v1/cart/user-123/items/1
Content-Type: application/json

{
  "quantity": 4
}

###

DELETE {{Cart.Api_HostAddress}}/api/v1/cart/user-123/items/1

###

DELETE {{Cart.Api_HostAddress}}/api/v1/cart/user-123

###
